// auto-generated
// Code generated by Root builder.

package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

type gui struct {
	win fyne.Window

	screens *fyne.Container
}

func newGUI() *gui {
	return &gui{}
}

func (g *gui) makeUI() fyne.CanvasObject {
	g.screens = container.NewStack(
		&widget.Label{Text: "SCREENS LOAD HERE", Alignment: 1, Wrapping: 0})

	return container.NewBorder(

		widget.NewToolbar(
			widget.NewToolbarAction(theme.FileIcon(), func() {}),
			widget.NewToolbarSeparator(),
			widget.NewToolbarAction(theme.MediaReplayIcon(), func() {}),
			widget.NewToolbarSpacer(),
			widget.NewToolbarAction(theme.HelpIcon(), func() {}),
		),
		nil,
		nil,
		nil,
		g.screens)
}

func (g *gui) makeWindow(a fyne.App) fyne.Window {
	w := a.NewWindow("main")
	g.win = w
	w.Resize(fyne.NewSize(380, 263))
	w.SetContent(g.makeUI())
	return w
}
