// auto-generated
// Code generated by GUI builder.

package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
	"image/color"
)

type screenGui struct {
	win fyne.Window

	active     *widget.Check
	label      *widget.Label
	location   *widget.Select
	name       *widget.Label
	primary    *widget.Check
	resolution *widget.Select
}

func newScreenGUI() *screenGui {
	return &screenGui{}
}

func (g *screenGui) makeUI() fyne.CanvasObject {
	g.active = widget.NewCheck("Active", func(b bool) {})
	g.label = widget.NewLabel("Label")
	g.location = &widget.Select{Options: []string{"Mirror", "LeftOf", "RightOf", "Above", "Below"}, Selected: "Mirror", OnChanged: func(s string) {}}
	g.name = widget.NewLabel("Screen Label")
	g.primary = widget.NewCheck("Primary", func(b bool) {})
	g.resolution = widget.NewSelect([]string{"Option 1", "Option 2"}, func(s string) {})

	return container.NewBorder(

		container.NewVBox(
			g.name,
			container.NewGridWithColumns(2,
				g.active,
				g.primary),
			g.location),
		nil,
		nil,
		nil,
		container.NewPadded(
			container.NewStack(
				&canvas.Rectangle{FillColor: &color.NRGBA{R: 0x30, G: 0x30, B: 0x30, A: 0xff}, StrokeColor: &color.NRGBA{R: 0x0, G: 0x0, B: 0x0, A: 0x0}, StrokeWidth: 5, CornerRadius: 0, Aspect: 0},
				container.NewCenter(
					container.NewVBox(
						g.label,
						g.resolution)))))
}

func (g *screenGui) makeWindow(a fyne.App) fyne.Window {
	w := a.NewWindow("screen.gui.go")
	g.win = w
	w.Resize(fyne.NewSize(293, 254))
	w.SetContent(g.makeUI())
	return w
}
