// auto-generated
// Code generated by GUI builder.

package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
	"image/color"
)

type screenGui struct {
	name       *widget.Label
	active     *widget.Check
	primary    *widget.Check
	location   *widget.Select
	resolution *widget.Label
}

func newScreenGUI() *screenGui {
	return &screenGui{}
}

func (g *screenGui) makeUI() fyne.CanvasObject {
	g.name = widget.NewLabel("Screen Label")
	g.active = widget.NewCheck("Active", func(b bool) {})
	g.primary = widget.NewCheck("Primary", func(b bool) {})
	g.location = &widget.Select{Options: []string{"Mirror", "LeftOf", "RightOf", "Above", "Below"}, Selected: "Primary", OnChanged: func(s string) {}}
	g.resolution = widget.NewLabel("Label")

	return container.NewBorder(

		container.NewVBox(
			g.name,
			container.NewGridWithColumns(2,
				g.active,
				g.primary),
			g.location),
		nil,
		nil,
		nil,
		container.NewPadded(
			container.NewStack(
				&canvas.Rectangle{FillColor: color.NRGBA{R: 0x30, G: 0x30, B: 0x30, A: 0xff}, StrokeColor: color.Gray16{Y: 0x0}, StrokeWidth: 5, CornerRadius: 0, Aspect: 1.6},
				container.NewCenter(
					g.resolution))))
}

func (g *screenGui) makeWindow(a fyne.App) fyne.Window {
	w := a.NewWindow("screen.gui.go")
	w.Resize(fyne.NewSize(289, 254))
	w.SetContent(g.makeUI())
	return w
}
