// auto-generated
// Code generated by Root builder.

package screenmanager

import (
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

type screensGui struct {
	win fyne.Window

	connected *fyne.Container
	offline   *fyne.Container
}

func newScreensGUI() *screensGui {
	return &screensGui{}
}

func (g *screensGui) makeUI() fyne.CanvasObject {
	g.connected = container.NewGridWithRows(1,
		container.NewStack(
			&canvas.Rectangle{FillColor: &color.NRGBA{R: 0xa0, G: 0xa0, B: 0xa0, A: 0xff}, StrokeColor: &color.NRGBA{R: 0x0, G: 0x0, B: 0x0, A: 0x0}, StrokeWidth: 4, CornerRadius: 2, Aspect: 0, TopRightCornerRadius: 0, TopLeftCornerRadius: 0, BottomRightCornerRadius: 0, BottomLeftCornerRadius: 0},
			container.NewCenter(
				&canvas.Text{Alignment: 0, Color: &color.NRGBA{R: 0x0, G: 0x0, B: 0x0, A: 0xff}, Text: "Monitor 1", TextSize: 11, TextStyle: fyne.TextStyle{Bold: false, Italic: false, Monospace: false, Symbol: false, TabWidth: 0, Underline: false}, FontSource: nil})))
	g.offline = container.NewHBox(
		widget.NewCheck("HDMI-1", func(b bool) {}))

	return container.NewStack(
		g.connected,
		container.NewBorder(
			nil,

			g.offline,
			nil,
			nil))
}

func (g *screensGui) makeWindow(a fyne.App) fyne.Window {
	w := a.NewWindow("screens")
	g.win = w
	w.Resize(fyne.NewSize(380, 263))
	w.SetContent(g.makeUI())
	return w
}
